// <auto-generated />
using System;
using ArtemisApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArtemisApi.Migrations
{
    [DbContext(typeof(ArtemisContext))]
    [Migration("20190215100750_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArtemisApi.Data.Entities.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Primary");

                    b.Property<string>("Secondary");

                    b.Property<int?>("WordSetId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("WordSetId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("ArtemisApi.Data.Entities.WordSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("WordSets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "WordSet {index}"
                        },
                        new
                        {
                            Id = 2,
                            Title = "WordSet {index}"
                        },
                        new
                        {
                            Id = 3,
                            Title = "WordSet {index}"
                        },
                        new
                        {
                            Id = 4,
                            Title = "WordSet {index}"
                        },
                        new
                        {
                            Id = 5,
                            Title = "WordSet {index}"
                        },
                        new
                        {
                            Id = 6,
                            Title = "WordSet {index}"
                        },
                        new
                        {
                            Id = 7,
                            Title = "WordSet {index}"
                        },
                        new
                        {
                            Id = 8,
                            Title = "WordSet {index}"
                        },
                        new
                        {
                            Id = 9,
                            Title = "WordSet {index}"
                        },
                        new
                        {
                            Id = 10,
                            Title = "WordSet {index}"
                        });
                });

            modelBuilder.Entity("ArtemisApi.Data.Entities.Word", b =>
                {
                    b.HasOne("ArtemisApi.Data.Entities.WordSet", "WordSet")
                        .WithMany("Words")
                        .HasForeignKey("WordSetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
